<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_robot">

  <!-- 定义一些常用的参数 -->
  <xacro:property name="base_radius" value="0.2" />
  <xacro:property name="wheel_radius" value="0.05" />
  <xacro:property name="wheel_thickness" value="0.03" />
  <xacro:property name="cylinder_height" value="0.1" />
  <xacro:property name="cylinder_radius" value="0.02" />
  <xacro:property name="lidar_height" value="0.05" />
  <xacro:property name="lidar_radius" value="0.04" />

  <!-- 圆形底盘 -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder radius="${base_radius}" length="0.01"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 0.8 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${base_radius}" length="0.01"/>
      </geometry>
    </collision>
  </link>

  <!-- 轮子宏定义 -->
  <xacro:macro name="wheel" params="name x y">
    <link name="${name}_link">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <origin xyz="${x} ${y} 0" rpy="0 1.57075 0"/>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <origin xyz="${x} ${y} 0" rpy="0 1.57075 0"/>
      </collision>
    </link>
    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}_link"/>
      <axis xyz="0 0 1"/>
      <origin xyz="${x} ${y} 0"/>
    </joint>
  </xacro:macro>

  <!-- 使用轮子宏定义四个轮子 -->
  <xacro:wheel name="front_left" x="-${base_radius * sqrt(2)/2}" y="${base_radius * sqrt(2)/2}" />
  <xacro:wheel name="front_right" x="${base_radius * sqrt(2)/2}" y="${base_radius * sqrt(2)/2}" />
  <xacro:wheel name="rear_left" x="-${base_radius * sqrt(2)/2}" y="-${base_radius * sqrt(2)/2}" />
  <xacro:wheel name="rear_right" x="${base_radius * sqrt(2)/2}" y="-${base_radius * sqrt(2)/2}" />

  <!-- 雷达和支架 -->
  <link name="cylinder_link">
    <visual>
      <geometry>
        <cylinder radius="${cylinder_radius}" length="${cylinder_height}"/>
      </geometry>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${cylinder_radius}" length="${cylinder_height}"/>
      </geometry>
    </collision>
  </link>

  <link name="lidar_link">
    <visual>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
      <material name="red">
        <color rgba="0.8 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
    </collision>
  </link>

  <!-- 将支架连接到底盘 -->
  <joint name="cylinder_joint" type="fixed">
    <parent link="base_link"/>
    <child link="cylinder_link"/>
    <origin xyz="0 0 ${cylinder_height/2}"/>
  </joint>

  <!-- 将雷达连接到支架 -->
  <joint name="lidar_joint" type="fixed">
    <parent link="cylinder_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 ${cylinder_height/2 + lidar_height}"/>
  </joint>

</robot>



